# pytorch tutorial

[파이토치 시작하기](https://tutorials.pytorch.kr/beginner/basics/tensorqs_tutorial.html)

In [1]:
import torch

In [2]:
t1 = torch.eye(3)
t1[:,1] = 1
print(t1)

tensor([[1., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.]])


## cat

In [3]:
# cat
print(torch.cat([t1,t1,t1],dim=1))
print(torch.cat([t1,t1,t1],dim=0))

tensor([[1., 1., 0., 1., 1., 0., 1., 1., 0.],
        [0., 1., 0., 0., 1., 0., 0., 1., 0.],
        [0., 1., 1., 0., 1., 1., 0., 1., 1.]])
tensor([[1., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.],
        [1., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.],
        [1., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.]])


## stack

In [4]:
# stack
print(t1)
print(torch.stack([t1,t1,t1],dim=0))

tensor([[1., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.]])
tensor([[[1., 1., 0.],
         [0., 1., 0.],
         [0., 1., 1.]],

        [[1., 1., 0.],
         [0., 1., 0.],
         [0., 1., 1.]],

        [[1., 1., 0.],
         [0., 1., 0.],
         [0., 1., 1.]]])


In [5]:
print(t1)
print(torch.stack([t1,t1,t1],dim=1))

tensor([[1., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.]])
tensor([[[1., 1., 0.],
         [1., 1., 0.],
         [1., 1., 0.]],

        [[0., 1., 0.],
         [0., 1., 0.],
         [0., 1., 0.]],

        [[0., 1., 1.],
         [0., 1., 1.],
         [0., 1., 1.]]])


In [6]:
print(t1)
print(torch.stack([t1,t1,t1],dim=2))

tensor([[1., 1., 0.],
        [0., 1., 0.],
        [0., 1., 1.]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [1., 1., 1.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [1., 1., 1.],
         [1., 1., 1.]]])


## torch multiplication

In [7]:
t1 = torch.eye(3)
t2 = torch.ones(3)

# 행렬 곱
print(torch.matmul(t1,t2)) 
# 원소 곱
print(torch.mul(t1,t2))

tensor([1., 1., 1.])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## numpy 변환

CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

In [8]:
t1 = torch.ones(3)
print(t1)
print(t1.numpy())

tensor([1., 1., 1.])
[1. 1. 1.]
